spring:
  application:
    name: pricing-service # Cambiar por el nombre del microservicio, por ejemplo, order-service
  config:
    import: configserver:http://localhost:8888 # URL del Config Server
  cloud:
    config:
      fail-fast: true # Detener si no se puede conectar al Config Server